### ISSUE TITLE
Mention compatibility in the README

### ISSUE THREAD

**Issue by feimosi** [lukechilds/when-dom-ready#2]
You should mention somewhere that people may need to add a polyfill or transpile the plugin. 
e.g. `[].includes()` or arrow functions are not yet so well supported. See:
http://kangax.github.io/compat-table/es2016plus/#test-Array.prototype.includes

**Comment by lukechilds** [comment]
Good old IE and Safari...

I'll transpile on my end and save everyone else the effort.

**Comment by lukechilds** [comment]
@feimosi Just published `v1.2.3` with `Array.includes` and arrow functions transpiled 👍

**Comment by feimosi** [comment]
Thanks, good job 👍 
Unfortunately Safari is the new IE and Android also comes into play...
