### ISSUE TITLE
Loading document readyState

### ISSUE THREAD

**Issue by craigfrancis** [lukechilds/when-dom-ready#26]
Where you have:

    const loadedStates = ['interactive', 'complete'];
    if (loadedStates.includes(doc.readyState)) {
    }

https://github.com/lukechilds/when-dom-ready/blob/mater/src/index.js#L22

Considering there are only 3 document ready states (loading/interactive/complete):

https://developer.mozilla.org/en-US/docs/Web/API/Document/readyState

Would it be better to do:

    if (doc.readyState !== 'loading') {
    }

Would be one less constant (the array of 2 stings), and a slightly faster string comparison (instead of checking if the array `includes`).

:-)

---

Just for comparison, I've been using the following in my JavaScript for a number of years, and I've not had any problems so far:

    if (document.readyState !== 'loading') {
        window.setTimeout(init); // Handle asynchronously
    } else {
        document.addEventListener('DOMContentLoaded', init);
    }

**Comment by lukechilds** [comment]
Thanks for the suggestion but this is not semantically equivalent. I don't want to check if the DOM "is not loading" I want to check if the DOM "is ready".

If there was a new readyState added like "preload" then `(document.readyState !== 'loading')` would be true which isn't what I want. An unlikely scenario but I'd rather be more explicit.

**Comment by craigfrancis** [comment]
Fair enough.

Personally, I don't think it will change (far too many websites rely on those 3 states).

And while it's not semantically equivalent, I'm simply looking for the document to not be in the "loading" state... rather than specifically be "interactive" or "complete".

Where I'd suggest any new states are just as likely to be after DOM Ready (or "loading"), than a new state before.

For example; while highly unlikely, it might be "unloading", as the user moves away to another page/tab, with the possibility of them coming back.

Whereas, I don't see how it's possible to have JavaScript running while it's in a "preload" state, as the act of running JavaScript will part of (or after) the loading process. Plus, "preloading" is a term more todo with caching:

https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content

:-)
