### ISSUE TITLE
Export as an UMD module / or is the build broken ?

### ISSUE THREAD

**Issue by Offirmo** [lukechilds/when-dom-ready#5]
This is a browser lib. However, it's written in CommonJS (aka. node modules), cf. src "module.exports = ..."

The file exposed in "dist" is still in CommonJS.

Thus this lib cant be used "as is" in a browser, it *must* be passed in a transpilation/bundling stack like browserify.

You should export an UMD module, which would work in any environment.

**Comment by Offirmo** [comment]
Example of easy solution: ditch babel, install typescript 2 and ask it to compile your JS to ES5/UMD (yes, the typescript compiler can do that)

**Comment by lukechilds** [comment]
When you say:

>Thus this lib cant be used "as is" in a browser

Are you referring to usage via:

```html
<script src="/node_modules/when-dom-ready/dist/index.js"></script>
```

**Comment by Offirmo** [comment]
@lukechilds definitely. Or alternatively

```html
<script src="https://unpkg.com/when-dom-ready@^1/dist/index.js"></script>
```

**Comment by lukechilds** [comment]
Hmmn, I'm kind of reluctant to do this, UMD seems like a messy hack that I've always avoided. I think the vast majority of frontend developers are using a package manager + module bundler now so this is unlikely to affect many people.

Although I can see the appeal of using something like script + unpkg for quick testing in dev tools.

I suppose the build process wouldn't really be any more complex than it is now. Can you specify what to transpile/leave with Typescript? e.g Currently with Babel I'm just Transpiling arrow fns and Array.includes for speed.

**Comment by Offirmo** [comment]
You'll be surprised... There is a whole world of JS dev outside of us webpack hipsters. Think of the massive number of jQuery users. You're also dismissing the other venerable module bundlers: AMD (which I use in personal projects with 100% ES6 code)

At least share your code in ES6, not in CommonJS (which is the *node* convention)

I'll send a PR.
