### ISSUE TITLE
Should you consider distributing a pre-built version?

### ISSUE THREAD

**Issue by thesublimeobject** [lukechilds/when-dom-ready#8]
I may be using this wrong, but I've been having trouble with this package recently since using `import whenDOMReady from 'when-dom-ready'` includes the file from /src. Given this is a non-compiled file using arrow functions, I am having to run it through webpack and babel-ify it myself. I don't ever have to do this with other libraries, making me feel like it's a common convention to pre-build the library for distribution, although I really might be wrong. I don't know a ton about common conventions for distributing npm modules. 

Should the module be running a build step that it is missing, or am I missing something? (Thanks, trying to learn and contribute; not trying to criticize).

**Comment by lukechilds** [comment]
Thanks for taking the time to report this issue :)

It is built before publishing to npm. The file [that should be included](https://github.com/lukechilds/when-dom-ready/blob/master/package.json#L5) should be in `dist` not `src`. It's not in git so you can't view it on GitHub but you can view it here: https://unpkg.com/when-dom-ready

Can you create a simple repo that reproduces the issue and link to it here so I can take a look?

**Comment by thesublimeobject** [comment]
Yeah, I noticed that in the prepublish script, but inside my node_modules there is no `dist` directory, only `src`. I will try to create a small repo for debugging after work.

**Comment by thesublimeobject** [comment]
Hey @lukechilds: It looks like yarn had an older version by ~two weeks (before you added the build step). Works fine now!

**Comment by lukechilds** [comment]
Ahhh, sorry yes, I did initially publish without transpilation before it got popular. Glad it's sorted 👍
